CREATE TABLE IF NOT EXISTS police_reports_2020 (
	item_number TEXT,
	district INT,
	location TEXT,
	disposition TEXT,
	signal_type TEXT,
	signal_description TEXT,
	occurred_date_time TEXT,
	charge_code TEXT,
	charge_description TEXT,
	offender_number TEXT,
	offender_id TEXT,
	offender_status TEXT,
	offender_race TEXT,
	offender_gender TEXT,
	offender_age TEXT,	
	victim_number TEXT,
	person_type TEXT,
	victim_race TEXT,
	victim_gender TEXT,
	victim_age TEXT,
	victim_fatal_status TEXT,
	hate_crime TEXT,
	report_type TEXT
);